"""
filename: 
     axpos.py
 
PURPOSE:
     set the position of multiplots

Routines:
     axpos: set the configuration of multiplots

Written by:
     Doosoo Yoon 
     Shanghai Astronomical Observatory
   
History:
     Written, 26 November 2017
"""
import numpy as np
import sys

class axpos:
    def __init__(self,multplt,pltx0=[50.,10.],plty0=[30.,10.],pltxs=200.,pltys=200.,pltxw=0.,pltyw=0.):
        """ 
        set the position of multiplots

        args:
            multplt: two digits integer, indicating the number of row & column 
                    (ex, 23 -> 2 rows and 3 columns)
                    
        keywords:
            pltx0/plty0: two elements array for [left margin, right margin]
            pltxs/pltys: (x/y) size of the plots
                         If single number is given, all plots have same (x/y) size.
                         If list of numbers is given, the length of the list should be same with
                         (x/y) size.
            pltxw/pltyw: gap between plots

            ### Note that all values will be scaled out. Hence, the exact values are meaningless,
            but the ratios between the variables are matter. ###

        return:
            self.winxs/self.winys: total (x,y) size of the figure.
                                   These are useful in setting the ratio of the figure. 
                                   (ex.  >>> plt.figure(figsize=(8.,8.*self.winys/self.winxs)))

	"""
        multplt = str(multplt)
        
        ny = int(multplt[0])
        nx = int(multplt[1])
        
        if (type(pltxs).__name__=='list'):
            if (len(pltxs) != nx):
                sys.exit('length of pltxs should be equal to nx.')
            self.pltxs = list(map(float,pltxs))
        else:
            self.pltxs = [float(pltxs) for i in range(nx)]
      
        if (type(pltys).__name__=='list'):
            if (len(pltys) != ny):
                sys.exit('length of pltys should be equal to ny.')
            self.pltys = list(map(float,pltys))
        else:
            self.pltys = [float(pltys) for i in range(ny)]
        
        self.winxs=np.sum(pltx0)+np.sum(self.pltxs)+(nx-1)*float(pltxw)
        self.winys=np.sum(plty0)+np.sum(self.pltys)+(ny-1)*float(pltyw)
    
        self.pltx0 = list(map(float,pltx0)); self.plty0 = list(map(float,plty0))
        self.pltxw = float(pltxw); self.pltyw = float(pltyw)
        
            
    def pos(self,numplt):
        """
        set the position of multiplots with given identifier

        args:
            numplt: three digits integer, indicating the number of (row/column/plot identifier)
                    --> same rule with matplotlib subplots

        return:
            list of [left,bottom,width,height]
            --> This can be used as
                >>> ax1 = plt.axes(self.plot(322))
        """
        
        numpltstr = str(numplt)
        
        row    = int(numpltstr[0])
        col    = int(numpltstr[1])
        posplt = int(numpltstr[2])
        
        # row position: increasing index for lower panels
        posrow = int((posplt-1) // col)
        # colum position: increasing index for right panels
        poscol = int(np.mod((posplt-1),col))
        
        if (row*col < posplt):
            sys.exit('plot number is out of range.')
        
        left   = (self.pltx0[0]+self.pltxw*poscol+np.sum(self.pltxs[:poscol]))/self.winxs
        width  = (self.pltxs[poscol])/self.winxs 
        bottom = (self.plty0[0]+self.pltyw*(row-1-posrow)+np.sum(self.pltys[posrow+1:]))/self.winys
        height = (self.pltys[posrow])/self.winys

        return [left,bottom,width,height]

    def subplots_adjust(self, fig):
        """
        manage the margins of sub plots
        used with multi plots generated by plt.add_subplots(...)

        args:
            fig: figure instance from 
                >>> fig = plt.figure()
        """


        fig.subplots_adjust(left=self.pltx0[0]/self.winxs,right=1-self.pltx0[1]/self.winxs \
                ,bottom=self.plty0[0]/self.winys,top=1-self.plty0[1]/self.winys \
                ,hspace=self.pltyw/self.pltys[0], wspace=self.pltxw/self.pltxs[0])

        return None
